#!/usr/bin/env python

from tfs import TfsClientService
import git, re, sys

class TFSGitHook(object):
    
    def __init__(self, revisions, config):
        self.client = TfsClientService(config['host'], config['username'], config['password'], None, None)
        self.revisions = self.processHistory(revisions)
        self.config = config
        
    def processHistory(self, revisions):
        bugRegex = re.compile(r'#([0-9]+)')
        revs = []
        
        for revision in revisions:
            prop = { 'id': revision['id'], 'name': revision['name'], 'message': revision['message'] }
            
            matches = bugRegex.findall(revision['message'])
            
            if matches is None:
                continue

            prop['item_ids'] = set()
            
            for id in matches:
                prop['item_ids'].add(id)

            revs.append(prop)

        return revs
        
    def getWorkItem(self, id):
        result = self.client.getWorkItem(id)
        if result:        
            revision = result['System.Rev']
            state = result['System.State']
            if revision and state:
                return int(revision), state    
        return None, None
        
    def addComments(self):
        for revision in self.revisions:        
            if revision['item_ids'] == None:
                continue

            print("link for %s" % revision['id'])
            for id in revision['item_ids']:
                (rev, state) = self.getWorkItem(id)
            
                if rev != None:
                    self.client.addWorkItemComment(id, rev, 
                        "{0}: {1} ({2};a=commit;h={3})".format(
                        revision['name'], 
                        revision['message'], 
                        self.config['weblink'], 
                        revision['id']))
    
if __name__ == '__main__':
    for line in sys.stdin.xreadlines():
        old, new, ref = line.strip().split(' ')
        revisions = git.get_revisions(old, new)
        
        config = { 
            'host': git.get_config('tfs-git-hook.host'), 
            'username' : git.get_config('tfs-git-hook.username'), 
            'password': git.get_config('tfs-git-hook.password'),
            'weblink': git.get_config('tfs-git-hook.weblink')
        }
        
        tfs = TFSGitHook(revisions, config)
        tfs.addComments()
